#!/bin/bash

# command:
# code --list-extensions | xargs -L 1 echo code --install-extension > install

code --install-extension alefragnani.project-manager
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dbaeumer.vscode-eslint
code --install-extension ecmel.vscode-html-css
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.code-runner
code --install-extension hwencc.html-tag-wrapper
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension k--kato.intellij-idea-keybindings
code --install-extension miclo.sort-typescript-imports
code --install-extension mikestead.dotenv
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension PKief.material-icon-theme
code --install-extension pnp.polacode
code --install-extension pranaygp.vscode-css-peek
code --install-extension rafamel.subtle-brackets
code --install-extension ritwickdey.LiveServer
code --install-extension ryanluker.vscode-coverage-gutters
code --install-extension SirTori.indenticator
code --install-extension uloco.theme-bluloco-dark
code --install-extension usernamehw.errorlens
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wix.vscode-import-cost
code --install-extension Wscats.eno
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.material-theme
code --install-extension Zignd.html-css-class-completion

exit 0
