#!/bin/bash

# command:
# code --list-extensions | xargs -L 1 echo code --install-extension > install

code --install-extension alefragnani.project-manager
code --install-extension apollographql.vscode-apollo
code --install-extension atomiks.moonlight
code --install-extension be5invis.toml
code --install-extension bpruitt-goddard.mermaid-markdown-syntax-highlighting
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dbaeumer.vscode-eslint
code --install-extension ecmel.vscode-html-css
code --install-extension ee92.folderize
code --install-extension EliverLara.sweet-vscode
code --install-extension EliverLara.sweet-vscode-icons
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.code-runner
code --install-extension foxundermoon.shell-format
code --install-extension golang.go
code --install-extension GraphQL.vscode-graphql
code --install-extension Guyutongxue.cpp-reference
code --install-extension hangxingliu.vscode-awk-hint
code --install-extension hangxingliu.vscode-systemd-support
code --install-extension hediet.vscode-drawio
code --install-extension hwencc.html-tag-wrapper
code --install-extension IBM.zopeneditor
code --install-extension JaimeOlivares.yuml
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension k--kato.intellij-idea-keybindings
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension luggage66.AWK
code --install-extension melak47.ninja-syntax
code --install-extension miclo.sort-typescript-imports
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension piotrpalarz.vscode-gitignore-generator
code --install-extension PKief.material-icon-theme
code --install-extension pnp.polacode
code --install-extension pranaygp.vscode-css-peek
code --install-extension rafamel.subtle-brackets
code --install-extension rashwell.tcl
code --install-extension ritwickdey.LiveServer
code --install-extension rust-lang.rust
code --install-extension ryanluker.vscode-coverage-gutters
code --install-extension shakram02.bash-beautify
code --install-extension SirTori.indenticator
code --install-extension surajbarkale.ninja
code --install-extension Thomaz.preparing
code --install-extension timonwong.shellcheck
code --install-extension twxs.cmake
code --install-extension uloco.theme-bluloco-dark
code --install-extension usernamehw.errorlens
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vsciot-vscode.vscode-arduino
code --install-extension vstirbu.vscode-mermaid-preview
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
code --install-extension Wscats.eno
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.material-theme
code --install-extension Zignd.html-css-class-completion
code --install-extension Zowe.vscode-extension-for-zowe

exit 0
